### ISSUE TITLE
Custom popperConfig properties are being overriden by defaults.

### ISSUE THREAD

**Issue by GexideL** [BayBreezy/nuxt-tour#120]
Hey, I've found an issue where manually set modifiers for popperConfig are being overriden by the default configuration.

```js
const steps: TourStep[] = [{
  popperConfig: {
    placement: 'bottom',
    modifiers: [{
      name: 'offset',
      options: {
        offset: [0, 50],
      },
    }],
  },
}];
```

Reproduction:
[https://codesandbox.io/p/devbox/fm74lt?file=%2Fapp.vue%3A18%2C6](https://codesandbox.io/p/devbox/fm74lt?file=%2Fapp.vue%3A18%2C6)

The offset "distance" should be 50px away from the reference, but it's only 14px as is the default value in the **defaultPopperConfig**.
Probably something to do with **defu** function as it does not override arrays.

**Comment by BayBreezy** [comment]
Thanks for bringing this to my attention. I thought defu did the same thing as merge from lodash.
Fixed in the last release
