### ISSUE TITLE
PostCSS breaking on adding tailwind plugin for nuxt-tour specifically

### ISSUE THREAD

**Issue by varun-nair-yocket** [BayBreezy/nuxt-tour#19]
Build breaks with postcss for this specific package. Error screenshot below:

![image](https://github.com/BayBreezy/nuxt-tour/assets/103422153/00d81405-f423-444d-9f57-99d341a0fa2e)

I am sharing stackblitz for reproduction:

> https://stackblitz.com/edit/nuxt-starter-sv2vxi?file=nuxt.config.ts,tailwind.config.js

**Comment by BayBreezy** [comment]
Hey,

Thanks for reporting this. I will investigate and let you know.

**Comment by BayBreezy** [comment]
I have seen this error before & how I solved it was by adding the tailwind plugins to the nuxt config under the tailwindcss object

```ts
import typography from '@tailwindcss/typography';
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss', 'nuxt-tour'],
  tailwindcss: {
    config: {
      plugins: [typography()],
    },
  },
});
```

Doing this in the reproduction also gets rid of the error.

**Comment by varun-nair-yocket** [comment]
Thanks, it worked! TS for the config options doesn't include plugins and was thus confused.

**Comment by BayBreezy** [comment]
Interesting... Are you saying that the TS version of the `tailwind.config` file is the issue here?
