### ISSUE TITLE
Cannot find module '@nuxt/icon'

### ISSUE THREAD

**Issue by sgoess** [BayBreezy/nuxt-tour#44]
Hi,

I just wanted to add nuxt-tour to my Nuxt 3 project and it failed right at the installation process. After adding the module to nuxt.config.ts, an error occurs:

`Cannot find module '@nuxt/icon' `

I created a reproduction sandbox for this issue:
https://codesandbox.io/p/devbox/nuxt-tour-ghfql5

As a workaround, I added `@nuxt/icon` to my project's devDependencies.

Cheers, Sebastian

**Comment by BayBreezy** [comment]
Thank you. I will get this fixed up soon.

**Comment by BayBreezy** [comment]
Hey @sgoess The last update fixed the issue. I did get an error tho... It requires the user to install typescript.. I don't really want to force users to install TS as its a big package.. but its needed.

What do you think? Should I install TS as a dep with the module?
